Repository charleszipp/azure-pipelines-tasks-terraform, pull requests merged in 2020-05, with the labels that each got.

#128 npm audit fixes
  TerraformCLI/package-lock.json
  TerraformCLI/package.json
  TerraformInstaller/package-lock.json
  TerraformInstaller/package.json
  package-lock.json
Labels: security

#129 Add support for import command
  TerraformCLI/.env-sample
  TerraformCLI/README.md
  TerraformCLI/src/index.ts
  TerraformCLI/src/terraform-import.ts
  TerraformCLI/src/terraform-runner.ts
  TerraformCLI/src/tests/scenarios-terraform.ts
  TerraformCLI/src/tests/terraform-import/default.env
  TerraformCLI/src/tests/terraform-import/default.vars
  TerraformCLI/src/tests/terraform-import/import-azurerm-with-options.env.ts
  TerraformCLI/src/tests/terraform-import/import-azurerm-with-options.ts
  TerraformCLI/src/tests/terraform-import/import-azurerm-with-secure-env-file.env.ts
  TerraformCLI/src/tests/terraform-import/import-azurerm-with-secure-env-file.ts
  TerraformCLI/src/tests/terraform-import/import-azurerm-with-secure-var-file.env.ts
  TerraformCLI/src/tests/terraform-import/import-azurerm-with-secure-var-file.ts
  TerraformCLI/src/tests/terraform-import/import-azurerm.env.ts
  TerraformCLI/src/tests/terraform-import/import-azurerm.ts
  TerraformCLI/src/tests/terraform-import/import_spec.ts
  TerraformCLI/task.json
  overview.md
Labels: enhancement

#130 Custom download url
  TerraformCLI/README.md
  TerraformInstaller/src/index.ts
  TerraformInstaller/src/installer.ts
  TerraformInstaller/task.json
Labels: enhancement

#131 Escape spaces in path
  TerraformCLI/src/terraform-runner.ts
  TerraformCLI/src/tests/terraform-plan/plan-azurerm-with-secure-var-file.env.ts
Labels: bug

#132 Init self configured
  TerraformCLI/README.md
  TerraformCLI/src/terraform-init.ts
  TerraformCLI/task.json
  overview.md
Labels: enhancement

#135 Add support for terraform output command
  TerraformCLI/src/index.ts
  TerraformCLI/src/terraform-output.ts
  TerraformCLI/src/terraform-runner.ts
  TerraformCLI/src/tests/assertions.ts
  TerraformCLI/src/tests/scenarios-terraform.ts
  TerraformCLI/src/tests/scenarios.ts
  TerraformCLI/src/tests/terraform-output/output-with-json-flag-defined.env.ts
  TerraformCLI/src/tests/terraform-output/output-with-json-flag-defined.ts
  TerraformCLI/src/tests/terraform-output/output-with-no-output-vars-defined.env.ts
  TerraformCLI/src/tests/terraform-output/output-with-no-output-vars-defined.ts
  TerraformCLI/src/tests/terraform-output/output-with-output-vars-defined.env.ts
  TerraformCLI/src/tests/terraform-output/output-with-output-vars-defined.ts
  TerraformCLI/src/tests/terraform-output/output_spec.ts
  TerraformCLI/task.json
  TerraformTemplates/sample/sample.tf
Labels: enhancement

#136 Update azurerm backend config names
  TerraformCLI/src/terraform-init.ts
  TerraformCLI/src/tests/terraform-init/init-with-backend-azurerm-with-ensure-backend.env.ts
  TerraformCLI/src/tests/terraform-init/init-with-backend-azurerm-with-ensure-existing-backend.env.ts
  TerraformCLI/src/tests/terraform-init/init-with-backend-azurerm.env.ts
  overview.md
Labels: bug

#142 First stab at making environmentServiceName optional
  TerraformCLI/src/terraform-apply.ts
  TerraformCLI/src/terraform-destroy.ts
  TerraformCLI/src/terraform-import.ts
  TerraformCLI/src/terraform-plan.ts
  TerraformCLI/src/terraform-refresh.ts
  TerraformCLI/src/terraform-runner.ts
  TerraformCLI/src/tests/terraform-apply/apply-without-envservicename.env.ts
  TerraformCLI/src/tests/terraform-apply/apply-without-envservicename.ts
  TerraformCLI/src/tests/terraform-apply/apply_spec.ts
  TerraformCLI/src/tests/terraform-destroy/destroy-without-envservicename.env.ts
  TerraformCLI/src/tests/terraform-destroy/destroy-without-envservicename.ts
  TerraformCLI/src/tests/terraform-destroy/destroy_spec.ts
  TerraformCLI/src/tests/terraform-import/import-without-envservicename.env.ts
  TerraformCLI/src/tests/terraform-import/import-without-envservicename.ts
  TerraformCLI/src/tests/terraform-import/import_spec.ts
  TerraformCLI/src/tests/terraform-plan/plan-without-envservicename.env.ts
  TerraformCLI/src/tests/terraform-plan/plan-without-envservicename.ts
  TerraformCLI/src/tests/terraform-plan/plan_spec.ts
  TerraformCLI/src/tests/terraform-refresh/refresh-without-envservicename.env.ts
  TerraformCLI/src/tests/terraform-refresh/refresh-without-envservicename.ts
  TerraformCLI/src/tests/terraform-refresh/refresh_spec.ts
  TerraformCLI/task.json
Labels: enhancement
