Repository charleszipp/azure-pipelines-tasks-terraform, pull requests merged in 2021-07, with the labels that each got.

#62 Fix bug that breaks azurerm backend on tf v1.1.x
  tasks/terraform-cli/src/backends/azurerm.ts
Labels: terraform-cli-task

#68 Resolves: Add native GitHub security and versioning dependency alerts
  .github/dependabot.yml
Labels: extension, security, terraform-cli-task, terraform-installer-task, terraform-plan-view

#72 Resolves: Add native GitHub continuous code security and quality analysis
  .github/workflows/codeql-analysis.yml
Labels: security

#105 Chzipp/fix dependabot updates
  pipelines/build/build_views_terraform_plan.yml
  tasks/terraform-cli/cucumber.js
  tasks/terraform-cli/package-lock.json
  tasks/terraform-cli/package.json
  tasks/terraform-cli/src/tests/steps/task-answers.steps.ts
  tasks/terraform-cli/src/tests/steps/task-context.steps.ts
  tasks/terraform-cli/src/tests/steps/task.steps.ts
  tasks/terraform-cli/tsconfig.json
  tasks/terraform-installer/package-lock.json
  tasks/terraform-installer/package.json
  views/terraform-plan/package-lock.json
  views/terraform-plan/package.json
Labels: dependencies

#112 0.9.2 tfx-cli depends on vulnerable pkgs
  package-lock.json
  package.json
Labels: dependencies
